#!/bin/bash
set -euo pipefail

# --- CONFIGURATION ---
VERSION_LONG="4.21.5"
VERSION_SHORT="4.21"
SPEC_FILE="openapi/openshift-openapi-spec-v4.21.json"

echo "🧹 Cleaning environment"
rm -rf v${VERSION_SHORT}* v${VERSION_LONG}*

# 1. GENERATION FUNCTION
generate_variant() {
    local suffix=$1
    local flags=$2
    local out_dir="v${VERSION_LONG}-${suffix}"
    
    echo "📦 Generating $out_dir ..."
    openapi2jsonschema "$SPEC_FILE" -o "$out_dir" $flags

    echo "📂 Mapping files"
    python3 - <<EOF
import os, json, shutil

source_dir = "$out_dir"
if not os.path.exists(source_dir): exit(0)
tmp_dir = source_dir + "_tmp"
os.makedirs(tmp_dir, exist_ok=True)

with open('$SPEC_FILE', 'r') as f:
    swagger = json.load(f)

gvk_map = {}
for key, value in swagger.get("definitions", {}).items():
    gvk = value.get("x-kubernetes-group-version-kind", [{}])[0]
    kind = gvk.get("kind", "").lower()
    group = gvk.get("group", "").lower()
    if not kind:
        kind = key.split(".")[-1].lower()
    gvk_map[key] = {"kind": kind, "group": group}

for f in os.listdir(source_dir):
    if not f.endswith('.json') or f == '_definitions.json': continue
    
    filepath = os.path.join(source_dir, f)
    
    # 🛡️ Ignore empty files (0 bytes)
    if os.path.getsize(filepath) == 0:
        continue

    # 🛡️ Ignore corruupt files that make json.load crash
    try:
        with open(filepath, 'r') as jf:
            data = json.load(jf)
    except Exception as e:
        print(f"⚠️ Ignoring invalid file generated by the tool: {f}")
        continue
    
    key = f.replace('.json', '')
    info = gvk_map.get(key, {})
    kind = info.get("kind", key.split(".")[-1].lower())
    group = info.get("group", "")

    if not kind: continue

    target_name = f"{kind}.json"
    if os.path.exists(os.path.join(tmp_dir, target_name)):
        target_name = f"{kind}-{group}.json" if group else f"{kind}-{key.replace('.','-')}.json"
    
    if "properties" not in data: data["properties"] = {}
    props = data["properties"]
    for p in ["apiVersion", "kind"]:
        if p not in props: props[p] = {"type": "string"}
    if "metadata" not in props: 
        props["metadata"] = {"type": "object"}

    with open(os.path.join(tmp_dir, target_name), 'w') as jf:
        json.dump(data, jf, indent=2)

shutil.rmtree(source_dir)
os.rename(tmp_dir, source_dir)
EOF
}

# 2. GENERATE VARIANTS
generate_variant "local" ""
generate_variant "standalone" "--stand-alone"
generate_variant "standalone-strict" "--stand-alone --strict"

# 3. CREATE PHYSICAL COPIES FOR GITHUB
echo "💾 Creating physical copies for Git..."
mkdir -p "v${VERSION_LONG}" && cp -r "v${VERSION_LONG}-standalone"/. "v${VERSION_LONG}/"
mkdir -p "v${VERSION_SHORT}" && cp -r "v${VERSION_LONG}/." "v${VERSION_SHORT}/"
mkdir -p "v${VERSION_SHORT}-local" && cp -r "v${VERSION_LONG}-local/." "v${VERSION_SHORT}-local/"
mkdir -p "v${VERSION_SHORT}-standalone" && cp -r "v${VERSION_LONG}-standalone/." "v${VERSION_SHORT}-standalone/"
mkdir -p "v${VERSION_SHORT}-standalone-strict" && cp -r "v${VERSION_LONG}-standalone-strict/." "v${VERSION_SHORT}-standalone-strict/"

echo "✅ Done. Generation has concluded successfully."
